/**
 * Catálogo de herramientas de investigación de consulta gratuita.
 *
 * Fuente de datos ÚNICA y tipada, compartida por el frontend (tabla y filtros) y el backend (el
 * asistente valida contra ella que la IA no recomiende herramientas inexistentes). No se escribe
 * ninguna fila dentro del JSX.
 *
 * Distinción deliberada en `accessType` — "gratuita" no significa "todo el contenido es abierto":
 *  - `open-access`  : consulta Y contenido abiertos.
 *  - `free-search`  : la búsqueda es gratuita, pero algún documento enlazado puede estar restringido.
 *  - `free-account` : uso gratuito, requiere crear una cuenta sin costo.
 */

export type ResearchToolAccess = "open-access" | "free-search" | "free-account";

export type ResearchToolCategory =
  | "academic-articles"
  | "books"
  | "datasets"
  | "current-news"
  | "patents"
  | "research-workflow";

export type ResearchToolFullText = "open" | "partial" | "depends-on-source" | "not-applicable";

export interface ResearchTool {
  id: string;
  name: string;
  category: ResearchToolCategory;
  description: string;
  accessType: ResearchToolAccess;
  fullTextAvailability: ResearchToolFullText;
  languages: string[];
  officialUrl: string;
  requiresAccount: boolean;
  lastVerifiedAt: string;
}

export const RESEARCH_TOOL_CATEGORY_LABELS: Record<ResearchToolCategory, string> = {
  "academic-articles": "Artículos y literatura académica",
  books: "Libros y recursos educativos",
  datasets: "Datos y estadísticas",
  "current-news": "Noticias y actualidad",
  patents: "Patentes y documentos empresariales",
  "research-workflow": "Organización e integridad",
};

export const RESEARCH_TOOL_ACCESS_LABELS: Record<ResearchToolAccess, string> = {
  "open-access": "Acceso abierto",
  "free-search": "Búsqueda gratuita",
  "free-account": "Gratuita con cuenta",
};

export const RESEARCH_TOOL_ACCESS_HINTS: Record<ResearchToolAccess, string> = {
  "open-access": "La consulta y el contenido son abiertos.",
  "free-search": "Buscar es gratis; algún documento enlazado puede estar restringido.",
  "free-account": "Uso gratuito, requiere una cuenta sin costo.",
};

export const RESEARCH_TOOL_FULLTEXT_LABELS: Record<ResearchToolFullText, string> = {
  open: "Abierto",
  partial: "Parcial",
  "depends-on-source": "Según la fuente",
  "not-applicable": "No aplica",
};

/** Fecha en que se compiló y comprobó el catálogo. Ver `tests/integration/researchLinks.test.ts`. */
const VERIFIED = "2026-08-30";

export const RESEARCH_TOOLS: ResearchTool[] = [
  // ---------- Artículos, repositorios y literatura académica ----------
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    category: "academic-articles",
    description: "Búsqueda académica asistida por IA, con resúmenes y grafo de citas.",
    accessType: "free-search",
    fullTextAvailability: "depends-on-source",
    languages: ["en"],
    officialUrl: "https://www.semanticscholar.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "openalex",
    name: "OpenAlex",
    category: "academic-articles",
    description: "Catálogo abierto de trabajos, autores, instituciones y fuentes de investigación.",
    accessType: "open-access",
    fullTextAvailability: "depends-on-source",
    languages: ["en"],
    officialUrl: "https://openalex.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "crossref",
    name: "Crossref Metadata Search",
    category: "academic-articles",
    description: "Metadatos, DOI y registros de publicaciones académicas.",
    accessType: "open-access",
    fullTextAvailability: "depends-on-source",
    languages: ["en"],
    officialUrl: "https://search.crossref.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "doaj",
    name: "DOAJ",
    category: "academic-articles",
    description: "Directorio de revistas y artículos de acceso abierto revisados por pares.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "es"],
    officialUrl: "https://doaj.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "core",
    name: "CORE",
    category: "academic-articles",
    description: "Agregador de investigación abierta procedente de repositorios de todo el mundo.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://core.ac.uk/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "base",
    name: "BASE",
    category: "academic-articles",
    description: "Buscador académico sobre repositorios institucionales y documentos abiertos.",
    accessType: "free-search",
    fullTextAvailability: "depends-on-source",
    languages: ["en", "de", "es"],
    officialUrl: "https://www.base-search.net/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "unpaywall",
    name: "Unpaywall",
    category: "academic-articles",
    description: "Localiza versiones legales de acceso abierto de artículos a partir de su DOI.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://unpaywall.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "pubmed",
    name: "PubMed",
    category: "academic-articles",
    description: "Referencias y resúmenes de literatura biomédica y de ciencias de la vida.",
    accessType: "free-search",
    fullTextAvailability: "depends-on-source",
    languages: ["en"],
    officialUrl: "https://pubmed.ncbi.nlm.nih.gov/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "pmc",
    name: "PubMed Central",
    category: "academic-articles",
    description: "Archivo gratuito de textos completos de literatura biomédica.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://pmc.ncbi.nlm.nih.gov/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "europe-pmc",
    name: "Europe PMC",
    category: "academic-articles",
    description: "Literatura y preprints biomédicos, con enlaces a datos y financiadores.",
    accessType: "open-access",
    fullTextAvailability: "partial",
    languages: ["en"],
    officialUrl: "https://europepmc.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "arxiv",
    name: "arXiv",
    category: "academic-articles",
    description: "Preprints de física, matemáticas, informática, estadística y economía.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://arxiv.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "biorxiv",
    name: "bioRxiv",
    category: "academic-articles",
    description: "Preprints de biología, previos a revisión por pares.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://www.biorxiv.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "medrxiv",
    name: "medRxiv",
    category: "academic-articles",
    description: "Preprints de ciencias de la salud y medicina clínica.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://www.medrxiv.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "hal",
    name: "HAL",
    category: "academic-articles",
    description: "Repositorio multidisciplinario abierto de la investigación francesa.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["fr", "en"],
    officialUrl: "https://hal.science/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "zenodo",
    name: "Zenodo",
    category: "academic-articles",
    description: "Repositorio abierto de publicaciones, datos y software con DOI.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://zenodo.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "osf",
    name: "Open Science Framework",
    category: "academic-articles",
    description: "Proyectos, preprints y materiales de investigación abiertos.",
    accessType: "free-account",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://osf.io/",
    requiresAccount: true,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "openaire",
    name: "OpenAIRE Explore",
    category: "academic-articles",
    description: "Resultados de investigación europea: publicaciones, datos y proyectos.",
    accessType: "open-access",
    fullTextAvailability: "depends-on-source",
    languages: ["en"],
    officialUrl: "https://explore.openaire.eu/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "scielo",
    name: "SciELO",
    category: "academic-articles",
    description: "Biblioteca de revistas de acceso abierto de América Latina, España y Portugal.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["es", "pt", "en"],
    officialUrl: "https://www.scielo.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "redalyc",
    name: "Redalyc",
    category: "academic-articles",
    description: "Publicaciones científicas iberoamericanas de acceso abierto.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["es", "pt", "en"],
    officialUrl: "https://www.redalyc.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "lareferencia",
    name: "LA Referencia",
    category: "academic-articles",
    description: "Red de repositorios de acceso abierto de América Latina.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["es", "pt"],
    officialUrl: "https://www.lareferencia.info/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "eric",
    name: "ERIC",
    category: "academic-articles",
    description: "Centro de información sobre investigación educativa.",
    accessType: "free-search",
    fullTextAvailability: "partial",
    languages: ["en"],
    officialUrl: "https://eric.ed.gov/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "dblp",
    name: "dblp",
    category: "academic-articles",
    description: "Bibliografía de publicaciones de informática.",
    accessType: "open-access",
    fullTextAvailability: "depends-on-source",
    languages: ["en"],
    officialUrl: "https://dblp.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "repec",
    name: "IDEAS/RePEc",
    category: "academic-articles",
    description: "Mayor bibliografía descentralizada de investigación económica.",
    accessType: "open-access",
    fullTextAvailability: "partial",
    languages: ["en"],
    officialUrl: "https://ideas.repec.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "nasa-ads",
    name: "NASA ADS",
    category: "academic-articles",
    description: "Sistema de datos astrofísicos: astronomía, física y ciencias planetarias.",
    accessType: "free-search",
    fullTextAvailability: "depends-on-source",
    languages: ["en"],
    officialUrl: "https://ui.adsabs.harvard.edu/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "agris",
    name: "AGRIS",
    category: "academic-articles",
    description: "Investigación agrícola y alimentaria de la FAO.",
    accessType: "free-search",
    fullTextAvailability: "depends-on-source",
    languages: ["en", "es", "fr"],
    officialUrl: "https://agris.fao.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },

  // ---------- Libros y recursos educativos ----------
  {
    id: "doab",
    name: "DOAB",
    category: "books",
    description: "Directorio de libros académicos de acceso abierto.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://doabooks.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "oapen",
    name: "OAPEN Library",
    category: "books",
    description: "Monografías académicas de acceso abierto, sobre todo en humanidades.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://library.oapen.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "open-library",
    name: "Open Library",
    category: "books",
    description: "Catálogo universal de libros con préstamo digital gratuito.",
    accessType: "free-account",
    fullTextAvailability: "partial",
    languages: ["en", "es"],
    officialUrl: "https://openlibrary.org/",
    requiresAccount: true,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "gutenberg",
    name: "Project Gutenberg",
    category: "books",
    description: "Libros de dominio público en múltiples formatos.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "es", "fr"],
    officialUrl: "https://www.gutenberg.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "internet-archive",
    name: "Internet Archive",
    category: "books",
    description:
      "Biblioteca digital de libros, documentos y páginas archivadas. Consultar es libre; solo el préstamo digital pide cuenta.",
    accessType: "free-search",
    fullTextAvailability: "partial",
    languages: ["en", "es"],
    officialUrl: "https://archive.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "google-books",
    name: "Google Books",
    category: "books",
    description: "Búsqueda de libros; la vista previa depende de los derechos de cada obra.",
    accessType: "free-search",
    fullTextAvailability: "partial",
    languages: ["es", "en"],
    officialUrl: "https://books.google.com/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "hathitrust",
    name: "HathiTrust Digital Library",
    category: "books",
    description: "Obras digitalizadas; lectura completa para dominio público.",
    accessType: "free-search",
    fullTextAvailability: "partial",
    languages: ["en"],
    officialUrl: "https://www.hathitrust.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "openstax",
    name: "OpenStax",
    category: "books",
    description: "Libros de texto universitarios abiertos y revisados por pares.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "es"],
    officialUrl: "https://openstax.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "libretexts",
    name: "LibreTexts",
    category: "books",
    description: "Materiales educativos abiertos y remezclables por disciplina.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "es"],
    officialUrl: "https://libretexts.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "ncbi-bookshelf",
    name: "NCBI Bookshelf",
    category: "books",
    description: "Libros y documentos biomédicos de consulta gratuita.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://www.ncbi.nlm.nih.gov/books/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },

  // ---------- Datos y estadísticas ----------
  {
    id: "world-bank",
    name: "World Bank Open Data",
    category: "datasets",
    description: "Indicadores de desarrollo de todos los países.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en", "es"],
    officialUrl: "https://data.worldbank.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "undata",
    name: "UNdata",
    category: "datasets",
    description: "Portal estadístico de las bases de datos de Naciones Unidas.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en"],
    officialUrl: "https://data.un.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "oecd-data",
    name: "OECD Data Explorer",
    category: "datasets",
    description: "Indicadores económicos, sociales y educativos de la OCDE.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en", "fr"],
    officialUrl: "https://data-explorer.oecd.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "imf-data",
    name: "IMF Data",
    category: "datasets",
    description: "Series macroeconómicas y financieras del Fondo Monetario Internacional.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en"],
    officialUrl: "https://www.imf.org/en/Data",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "eurostat",
    name: "Eurostat",
    category: "datasets",
    description: "Estadísticas oficiales de la Unión Europea.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en", "de", "fr"],
    officialUrl: "https://ec.europa.eu/eurostat/databrowser/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "our-world-in-data",
    name: "Our World in Data",
    category: "datasets",
    description: "Datos, gráficas y análisis sobre problemas globales.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "es"],
    officialUrl: "https://ourworldindata.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "google-dataset-search",
    name: "Google Dataset Search",
    category: "datasets",
    description: "Buscador de conjuntos de datos publicados en la web.",
    accessType: "free-search",
    fullTextAvailability: "depends-on-source",
    languages: ["es", "en"],
    officialUrl: "https://datasetsearch.research.google.com/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "data-gov",
    name: "Data.gov",
    category: "datasets",
    description: "Datos abiertos del gobierno de Estados Unidos.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en"],
    officialUrl: "https://data.gov/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "datos-gob-mx",
    name: "datos.gob.mx",
    category: "datasets",
    description: "Portal de datos abiertos del gobierno de México.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["es"],
    officialUrl: "https://datos.gob.mx/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "inegi",
    name: "INEGI Datos Abiertos",
    category: "datasets",
    description: "Estadística y geografía oficiales de México.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["es"],
    officialUrl: "https://www.inegi.org.mx/datosabiertos/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "who-gho",
    name: "WHO Global Health Observatory",
    category: "datasets",
    description: "Indicadores mundiales de salud de la OMS.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en", "es"],
    officialUrl: "https://www.who.int/data/gho",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "faostat",
    name: "FAOSTAT",
    category: "datasets",
    description: "Datos de agricultura, alimentación y desarrollo rural.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en", "es"],
    officialUrl: "https://www.fao.org/faostat/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "ilostat",
    name: "ILOSTAT",
    category: "datasets",
    description: "Estadísticas laborales de la Organización Internacional del Trabajo.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en", "es"],
    officialUrl: "https://ilostat.ilo.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },

  // ---------- Noticias y actualidad ----------
  {
    id: "gdelt",
    name: "GDELT",
    category: "current-news",
    description: "Monitoreo abierto de noticias mundiales, con datos descargables.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en"],
    officialUrl: "https://www.gdeltproject.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "google-news",
    name: "Google News",
    category: "current-news",
    description: "Agregador gratuito; los enlaces externos pueden tener muro de pago.",
    accessType: "free-search",
    fullTextAvailability: "depends-on-source",
    languages: ["es", "en"],
    officialUrl: "https://news.google.com/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "ap-news",
    name: "AP News",
    category: "current-news",
    description: "Agencia de noticias internacional de consulta gratuita.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "es"],
    officialUrl: "https://apnews.com/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "bbc-news",
    name: "BBC News",
    category: "current-news",
    description: "Noticias y análisis internacionales.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "es"],
    officialUrl: "https://www.bbc.com/news",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "un-news",
    name: "UN News",
    category: "current-news",
    description: "Actualidad oficial del sistema de Naciones Unidas.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["es", "en"],
    officialUrl: "https://news.un.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "who-newsroom",
    name: "WHO Newsroom",
    category: "current-news",
    description: "Comunicados y alertas sanitarias de la OMS.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "es"],
    officialUrl: "https://www.who.int/news-room",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "nasa-news",
    name: "NASA News",
    category: "current-news",
    description: "Novedades de ciencia, tecnología y exploración espacial.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://www.nasa.gov/news/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "the-conversation",
    name: "The Conversation",
    category: "current-news",
    description: "Análisis de actualidad escrito por personal académico, con licencia abierta.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["es", "en"],
    officialUrl: "https://theconversation.com/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },

  // ---------- Patentes y documentos empresariales ----------
  {
    id: "google-patents",
    name: "Google Patents",
    category: "patents",
    description: "Búsqueda de patentes de múltiples oficinas, con texto completo.",
    accessType: "free-search",
    fullTextAvailability: "open",
    languages: ["en", "es"],
    officialUrl: "https://patents.google.com/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "espacenet",
    name: "Espacenet",
    category: "patents",
    description: "Base de patentes internacionales de la Oficina Europea de Patentes.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "de", "fr"],
    officialUrl: "https://worldwide.espacenet.com/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "patentscope",
    name: "WIPO PATENTSCOPE",
    category: "patents",
    description: "Solicitudes internacionales de patente (PCT) y colecciones nacionales.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en", "es", "fr"],
    officialUrl: "https://patentscope.wipo.int/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "uspto",
    name: "USPTO Patent Public Search",
    category: "patents",
    description: "Búsqueda oficial de patentes de Estados Unidos.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://ppubs.uspto.gov/pubwebapp/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "sec-edgar",
    name: "SEC EDGAR",
    category: "patents",
    description: "Documentos corporativos y financieros presentados ante la SEC.",
    accessType: "open-access",
    fullTextAvailability: "open",
    languages: ["en"],
    officialUrl: "https://www.sec.gov/edgar/search/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },

  // ---------- Organización e integridad de la investigación ----------
  {
    id: "zotero",
    name: "Zotero",
    category: "research-workflow",
    description: "Gestor bibliográfico gratuito con sincronización y citas automáticas.",
    accessType: "free-account",
    fullTextAvailability: "not-applicable",
    languages: ["es", "en"],
    officialUrl: "https://www.zotero.org/",
    requiresAccount: true,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "jabref",
    name: "JabRef",
    category: "research-workflow",
    description: "Gestor bibliográfico de código abierto basado en BibTeX.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en", "es"],
    officialUrl: "https://www.jabref.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "opencitations",
    name: "OpenCitations",
    category: "research-workflow",
    description: "Datos abiertos de citaciones académicas.",
    accessType: "open-access",
    fullTextAvailability: "not-applicable",
    languages: ["en"],
    officialUrl: "https://opencitations.net/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
  {
    id: "datacite-commons",
    name: "DataCite Commons",
    category: "research-workflow",
    description: "Búsqueda de DOI, autores, organizaciones y repositorios.",
    accessType: "open-access",
    fullTextAvailability: "depends-on-source",
    languages: ["en"],
    officialUrl: "https://commons.datacite.org/",
    requiresAccount: false,
    lastVerifiedAt: VERIFIED,
  },
];

/** Índice por id — lo usa el asistente para rechazar identificadores inexistentes. */
export const RESEARCH_TOOL_IDS: ReadonlySet<string> = new Set(RESEARCH_TOOLS.map((t) => t.id));

export function getResearchTool(id: string): ResearchTool | undefined {
  return RESEARCH_TOOLS.find((t) => t.id === id);
}

/** Idiomas presentes en el catálogo, ordenados — alimenta el filtro sin duplicar la lista. */
export function researchToolLanguages(): string[] {
  return [...new Set(RESEARCH_TOOLS.flatMap((t) => t.languages))].sort();
}
